const vino = [
    {
        name: "Blood of Jupiter",
        variety: ["Sangiovese", "Red"],
        winery: "Alpha Box & Dice",
        region: "McLaren Vale",
        style: "Traditional",
        year: 2020,
        img: "https://cdn.shopify.com/s/files/1/0576/3517/6548/products/ABD-BOJ2019_1920x1920.png?v=1649208984",
        desc: "Sangiovese has been kicking around Mclaren Vale since the 80s, and the Blood of Jupiter demonstrates why it's a regional hero: the signature flavours of sour cherries, moreish acidity with a lick of spice fresh from the baker's pantry.  2020 sees a more brooding and earthy version with tannins and structure entwined with a rustic charm that evokes ideas of crispy porchetta spinning slowly over some coals.",
    },
    {
        name: "Naranjito Verdelho ",
        variety: ["Verdelho", "Orange"],
        winery: "Somos",
        region: "McLaren Vale",
        style: "Lo-Fi",
        year: 2021,
        img: "https://sometimes-always.imgix.net/2022/03/22-02-15-10copy_eb488525-6cdc-4d98-9f5a-656a099dffe4.png?w=500&h=916&dpr=1&crop=false&fit=max&auto=format",
        desc: "Somos means “we are” in Spanish and these are the wines we love to drink, and in essence they are what we are about. Youthful, juicy, vibrant and textural. Naranjito contains all the immediacy and juiciness that aids drinkability yet still has plenty of structure and intrigue. Made with Verdelho from biodynamically handled vineyards, this Lo-Fi wine has intense texture and chewy tannin, backed up by a generous palate of mandarin peel, baked pear, and ginger spice.",
    },
    {
        name: "Golden Mullet Fury",
        variety: ["Semillon Muscat Riesling", "Orange"],
        winery: "Alpha Box & Dice",
        region: "McLaren Vale",
        style: "Progressive",
        year: 2020,
        img: "https://sometimes-always.imgix.net/2021/10/ABD-GMF-20__66919.1632267643.1280.1280.png?w=500&h=916&dpr=1&crop=false&fit=max&auto=format",
        desc: "The 2020 vintage has evolved some more. Structure and richness of Semillon, fruit brightness and of Muscat, and a splash of Botrytis Riesling for that business-up-front, party-in-the-back affair.",
    },
    {
        name: "Jade and Jasper",
        variety: ["Fiano", "White"],
        winery: "Uncle Zelo",
        region: "Riverland",
        style: "Progressive",
        year: 2022,
        img: "https://sometimes-always.imgix.net/2022/07/21-07-12-SA-Bottles-5_f7e20f18-7f9a-4b10-87c5-d8978a176315.png?w=500&h=912&dpr=1&crop=false&fit=max&auto=format",
        desc: "One thing that gladdens our hearts, is the great Italian varieties flowing forth from great growers in the Riverland…. Such a good thing. Here those fine folk at Unico Zelo, grab some of that mighty delicious Riverland Fiano from the ace Ricca Terra vineyards and weave their magic. Zesty and vivid with flavours of citrus, green apples and pear fruits with hints of ginger, almonds and white flowers. Walks the tightrope between texture and acidity with aplomb and it’s damn-delicious, lip-smacking drinking for summer.",
    },
    {
        name: "Golden",
        variety: ["Semillon Muscat Gewürztraminer", "Orange"],
        winery: "Italian Plastic",
        region: "Fleurieu Peninsula",
        style: "Lo-Fi",
        year: 2021,
        img: "https://sometimes-always.imgix.net/2021/11/GOLDEN-1.png?w=500&h=912&dpr=1&crop=false&fit=max&auto=format",
        desc: "An orange wine that hits the sweet (er, savoury) spot between exotic wonder and dusty moreishness. With up-front aromatics and florals, it starts out all skinsy and tropical with notes of tangerine and stonefruits. Refreshingly dry on the end for an easy-drinking finish. Textural and interesting, fun and chewy. Take a bite, come back for seconds.",
    },
    {
        name: "No.3",
        variety: ["Riesling", "White"],
        winery: "RieslingFreak",
        region: "Clare Valley",
        style: "Traditional",
        year: 2022,
        img: "https://sometimes-always.imgix.net/2022/07/22-07-21-1009copy.png?w=500&h=912&dpr=1&crop=false&fit=max&auto=format",
        desc: "This wine comes from John Hughes of riesling fame (not filmmaking fame). But if it was a Hollywood foray, this would be his Sixteen Candles or Breakfast Club - a classic, to be enjoyed young, on repeat. From the family vineyard in White Hutt, it’s dry with ripe citrus, honeydew and orange. That’s a wrap.",
    },
];

export default vino;
